development:
  url: redis://<%= ENV['REDIS_HOST'] || 'localhost' %>:<%= ENV['REDIS_PORT'] || '6379' %>/1
  channel_prefix: spotlight_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] || 'redis' %>:<%= ENV['REDIS_PORT'] || '6379' %>/1
  channel_prefix: spotlight_production
